<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <AssemblyName>Pencils</AssemblyName>
        <RootNamespace>Pencils</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
      <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
      <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
      <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
      <PackageReference Include="Vortice.Vulkan" Version="3.2.3" />
    </ItemGroup>

</Project>
